import Image from 'next/image';
import Link from 'next/link';
import { Suspense } from 'react';
import { localPath, pick, type Locale, type Service, type Insight } from '@/lib/content/types';
import { t } from '@/lib/i18n';
import { Arrow, ArrowUp, Plus, Globe } from './icons';
import { Breadcrumb, ContactBand, Eyebrow, InsightCard, PageIntro, TextLink } from './shared';
import { ServiceExplorer } from './service-explorer';
import { InsightBrowser } from './insight-browser';
import { EnquiryForm } from './enquiry-form';

export function HomePage({ locale, services, insights }: { locale: Locale; services: Service[]; insights: Insight[] }) {
  return <>
    <section className="home-hero shell">
      <Eyebrow>{t(locale, 'Kreston NBB · Saudi Arabia', 'كريستون إن بي بي · المملكة العربية السعودية')}</Eyebrow>
      <div className="hero-heading"><h1>{t(locale, 'Saudi insight.', 'رؤية سعودية.')}<br /><span>{t(locale, 'Confident decisions.', 'قرارات واثقة.')}</span></h1><div className="hero-description"><p>{t(locale, 'Audit, tax and advisory for the decisions that move your business forward.', 'المراجعة والضرائب والاستشارات للقرارات التي تدفع أعمالك إلى الأمام.')}</p><Link className="text-link" href={localPath(locale, 'contact')}>{t(locale, 'Request a consultation', 'طلب استشارة')}<ArrowUp /></Link></div></div>
      <div className="hero-photo"><Image src="/images/riyadh.jpg" alt={t(locale, 'The patterned facade of King Fahad National Library and Al Faisaliah Tower in Riyadh', 'واجهة مكتبة الملك فهد الوطنية وبرج الفيصلية في الرياض')} fill priority sizes="(max-width: 700px) 100vw, 92vw" /><div className="photo-caption"><span className="location-dot" />{t(locale, 'Riyadh, Saudi Arabia', 'الرياض، المملكة العربية السعودية')}</div><div className="photo-corner" aria-hidden="true"><span/><span/></div></div>
      <div className="hero-footnote"><span>{t(locale, 'Rooted in Saudi Arabia. Connected through Kreston.', 'جذورنا في السعودية. وتواصلنا عبر كريستون.')}</span><a href="#expertise">{t(locale, 'Discover our expertise', 'اكتشف خبراتنا')}<Arrow className="down" /></a></div>
    </section>
    <section className="firm-intro shell section-space"><Eyebrow number="01">{t(locale, 'The NBB perspective', 'رؤية إن بي بي')}</Eyebrow><div><h2>{t(locale, 'Behind every decision,', 'وراء كل قرار،')}<br /><span className="muted-heading">{t(locale, 'a clearer understanding.', 'فهم أوضح.')}</span></h2><div className="firm-intro-copy"><p>{t(locale, 'Business moves forward when you can see the whole picture. We bring financial expertise and an understanding of Saudi business to the questions that matter to you.', 'تتقدم الأعمال عندما تتضح الصورة كاملة. نقدم الخبرة المالية وفهم بيئة الأعمال السعودية لمعالجة الأسئلة التي تهمك.')}</p><TextLink href={localPath(locale, 'about')}>{t(locale, 'Get to know our firm', 'تعرّف على شركتنا')}</TextLink></div></div></section>
    <section id="expertise" className="expertise-section"><div className="shell"><div className="section-heading"><div><Eyebrow number="02">{t(locale, 'Our expertise', 'خبراتنا')}</Eyebrow><h2>{t(locale, 'The right expertise.', 'الخبرة المناسبة.')}<br /><span>{t(locale, 'At the right moment.', 'في اللحظة المناسبة.')}</span></h2></div><p>{t(locale, 'From the detail in your accounts to the direction of your business. Six connected areas of expertise.', 'من تفاصيل حساباتك إلى اتجاه أعمالك. ستة مجالات مترابطة من الخبرة.')}</p></div><ServiceExplorer services={services} locale={locale} /></div></section>
    <section className="approach-section shell section-space"><div className="approach-photo"><Image src="/images/saudi-business.jpg" alt={t(locale, 'A business discussion in a Saudi setting', 'مناقشة أعمال في بيئة سعودية')} fill sizes="(max-width: 800px) 100vw, 45vw" /><span className="vertical-caption">{t(locale, 'A closer understanding', 'فهم أعمق')}</span></div><div className="approach-copy"><Eyebrow number="03">{t(locale, 'How we think', 'كيف نفكر')}</Eyebrow><h2>{t(locale, 'Your business.', 'أعمالك.')}<br />{t(locale, 'Understood.', 'نفهمها.')}</h2><p>{t(locale, 'Useful advice begins with listening. Understanding where you are, what you’re building, and the decisions you need to make.', 'تبدأ المشورة المفيدة بالاستماع. بفهم واقعك وما تطمح إلى بنائه والقرارات التي تحتاج إلى اتخاذها.')}</p><div className="approach-points"><div><span>01</span><h3>{t(locale, 'A local perspective', 'رؤية محلية')}</h3><p>{t(locale, 'Advice shaped by the Saudi business environment.', 'مشورة تراعي بيئة الأعمال السعودية.')}</p></div><div><span>02</span><h3>{t(locale, 'A practical conversation', 'مناقشة عملية')}</h3><p>{t(locale, 'Clear questions. Considered advice. Useful next steps.', 'أسئلة واضحة ومشورة مدروسة وخطوات عملية.')}</p></div><div><span>03</span><h3>{t(locale, 'A wider connection', 'تواصل أوسع')}</h3><p>{t(locale, 'Access to the Kreston network when your work crosses borders.', 'تواصل مع شبكة كريستون عندما تتجاوز أعمالك الحدود.')}</p></div></div><TextLink href={localPath(locale, 'about')}>{t(locale, 'Our approach to advice', 'منهجنا في تقديم المشورة')}</TextLink></div></section>
    <section className="perspectives-section section-space"><div className="shell"><div className="section-heading"><div><Eyebrow number="04">{t(locale, 'Perspectives', 'رؤى')}</Eyebrow><h2>{t(locale, 'A little perspective.', 'رؤية أوضح.')}<br /><span className="muted-heading">{t(locale, 'A better next step.', 'وخطوة أفضل.')}</span></h2></div><TextLink href={localPath(locale, 'insights')}>{t(locale, 'Explore all perspectives', 'اكتشف جميع الرؤى')}</TextLink></div><div className="home-insights"><InsightCard locale={locale} insight={insights[0]} featured /><div className="insight-side">{insights.slice(1).map(insight => <article key={insight.slug}><span className="eyebrow">{insight.category === 'audit' ? t(locale, 'Audit & assurance', 'المراجعة والتأكيد') : t(locale, 'Financial advisory', 'الاستشارات المالية')}</span><h3><Link href={localPath(locale, 'insights/' + insight.slug)}>{pick(insight.title, locale)}</Link></h3><p>{pick(insight.summary, locale)}</p><Link className="small-arrow-link" href={localPath(locale, 'insights/' + insight.slug)} aria-label={pick(insight.title, locale)}><ArrowUp /></Link></article>)}</div></div></div></section>
    <ContactBand locale={locale} />
  </>;
}

export function ServicesPage({ locale, services }: { locale: Locale; services: Service[] }) {
  return <><PageIntro locale={locale} label={t(locale, 'Our expertise', 'خبراتنا')} title={t(locale, 'Expertise for what comes next.', 'خبرة للخطوة القادمة.')} summary={t(locale, 'Six connected areas of expertise. One considered view of your business.', 'ستة مجالات مترابطة من الخبرة. ورؤية مدروسة لأعمالك.')} /><section className="shell services-directory">{services.map(service => <article key={service.id} className="directory-row"><span className="mono">{service.number}</span><div><h2><Link href={localPath(locale, 'services/' + service.slug)}>{pick(service.name, locale)}</Link></h2><span className="service-tagline">{pick(service.short, locale)}</span></div><p>{pick(service.summary, locale)}</p><Link className="small-arrow-link" href={localPath(locale, 'services/' + service.slug)} aria-label={pick(service.name, locale)}><ArrowUp /></Link></article>)}</section><section className="shell service-help"><Eyebrow>{t(locale, 'Start with your question', 'ابدأ بسؤالك')}</Eyebrow><h2>{t(locale, 'Not sure where to begin?', 'لست متأكداً من أين تبدأ؟')}</h2><TextLink href={localPath(locale, 'contact')}>{t(locale, 'Let’s work it out together', 'لنحدد الخطوة المناسبة معاً')}</TextLink></section><ContactBand locale={locale}/></>;
}

export function ServicePage({ locale, service, services, insights }: { locale: Locale; service: Service; services: Service[]; insights: Insight[] }) {
  const faq = [
    { q: t(locale, 'Where does an engagement begin?', 'كيف يبدأ العمل؟'), a: t(locale, 'With a conversation about your organisation, your priorities and the information available. The scope and next steps are agreed before work begins.', 'بمحادثة حول منشأتك وأولوياتك والمعلومات المتاحة. يُتفق على نطاق العمل والخطوات التالية قبل البدء.') },
    { q: t(locale, 'What should I prepare for a first conversation?', 'ماذا أُعدّ للمحادثة الأولى؟'), a: t(locale, 'A brief overview of your business, the question you need to address and any relevant timelines. Please do not send confidential documents through the website form.', 'نبذة عن أعمالك والمسألة التي تود معالجتها وأي مواعيد ذات صلة. يرجى عدم إرسال مستندات سرية عبر نموذج الموقع.') },
    { q: t(locale, 'Can we discuss more than one service?', 'هل يمكن مناقشة أكثر من خدمة؟'), a: t(locale, 'Yes. Business questions often connect several areas of expertise. Describe what you need and we can discuss the appropriate scope.', 'نعم. غالباً ما تربط أسئلة الأعمال بين عدة مجالات من الخبرة. وضّح احتياجاتك لنناقش نطاق العمل المناسب.') },
  ];
  return <>
    <section className="service-hero"><div className="shell"><Breadcrumb locale={locale} items={[{ name: t(locale, 'Our expertise', 'خبراتنا'), href: localPath(locale, 'services') }, { name: pick(service.name, locale) }]} /><Eyebrow number={service.number}>{pick(service.name, locale)}</Eyebrow><div className="intro-grid"><h1>{pick(service.short, locale)}</h1><div className="intro-description"><p>{pick(service.summary, locale)}</p><Link className="button button-light" href={localPath(locale, 'contact?service=' + service.id)}>{t(locale, 'Discuss your needs', 'ناقش احتياجاتك')}<ArrowUp /></Link></div></div></div><span className="service-watermark" aria-hidden="true">{service.number}</span></section>
    <section className="service-body shell section-space"><aside><span className="eyebrow">{t(locale, 'On this page', 'في هذه الصفحة')}</span><a href="#overview">{t(locale, 'Overview', 'نظرة عامة')}</a><a href="#how-we-help">{t(locale, 'How we help', 'كيف نساعدك')}</a><a href="#our-approach">{t(locale, 'Our approach', 'منهجنا')}</a><a href="#questions">{t(locale, 'Your questions', 'أسئلتك')}</a></aside><div className="service-content"><section id="overview"><Eyebrow>{t(locale, 'A clearer picture', 'صورة أوضح')}</Eyebrow><h2>{pick(service.name, locale)}</h2><p className="large-copy">{pick(service.introduction, locale)}</p></section><section id="how-we-help"><Eyebrow>{t(locale, 'How we help', 'كيف نساعدك')}</Eyebrow><div className="offering-list">{service.offerings.map((offering, index) => <div key={offering.name.en}><span className="mono">{'0' + (index + 1)}</span><div><h3>{pick(offering.name, locale)}</h3><p>{pick(offering.description, locale)}</p></div><Plus /></div>)}</div></section><section id="our-approach"><Eyebrow>{t(locale, 'Our approach', 'منهجنا')}</Eyebrow><h2>{t(locale, 'Clarity at every step.', 'وضوح في كل خطوة.')}</h2><div className="process-grid">{[
      [t(locale, 'Understand', 'نفهم'), t(locale, 'Your business, your priorities and the decision in front of you.', 'أعمالك وأولوياتك والقرار الذي تواجهه.')],
      [t(locale, 'Define', 'نحدد'), t(locale, 'A considered scope, the right information and an agreed way forward.', 'نطاقاً مدروساً ومعلومات مناسبة ومساراً متفقاً عليه.')],
      [t(locale, 'Advise', 'نقدم المشورة'), t(locale, 'Clear findings and practical recommendations you can discuss and act on.', 'نتائج واضحة وتوصيات عملية قابلة للمناقشة والتنفيذ.')],
    ].map(([title, body], index) => <div key={title}><span className="mono">{'0' + (index + 1)}</span><h3>{title}</h3><p>{body}</p></div>)}</div></section><section id="questions"><Eyebrow>{t(locale, 'Your questions', 'أسئلتك')}</Eyebrow><h2>{t(locale, 'Before we begin.', 'قبل أن نبدأ.')}</h2><div className="faq-list">{faq.map(item => <details key={item.q}><summary>{item.q}<Plus /></summary><p>{item.a}</p></details>)}</div></section></div></section>
    <section className="related-section shell"><div className="section-heading"><h2>{t(locale, 'Connected expertise.', 'خبرات مترابطة.')}</h2><TextLink href={localPath(locale, 'services')}>{t(locale, 'All services', 'جميع الخدمات')}</TextLink></div><div className="related-services">{services.filter(item => item.id !== service.id).slice(0, 2).map(item => <Link href={localPath(locale, 'services/' + item.slug)} key={item.id}><span className="mono">{item.number}</span><h3>{pick(item.name, locale)}</h3><ArrowUp /></Link>)}</div><div className="related-reading"><span>{t(locale, 'A useful perspective', 'رؤية مفيدة')}</span><Link href={localPath(locale, 'insights/' + insights[1].slug)}>{pick(insights[1].title, locale)}<Arrow /></Link></div></section><ContactBand locale={locale} />
  </>;
}

export function AboutPage({ locale }: { locale: Locale }) {
  return <><PageIntro locale={locale} label={t(locale, 'Our firm', 'عن الشركة')} title={t(locale, 'A closer understanding. A wider perspective.', 'فهم أعمق. ورؤية أوسع.')} summary={t(locale, 'Kreston NBB Saudi brings audit, tax and advisory expertise to businesses operating in the Kingdom.', 'تقدم كريستون إن بي بي السعودية خبرات المراجعة والضرائب والاستشارات للمنشآت العاملة في المملكة.')} /><div className="about-banner shell"><div><Image src="/images/riyadh.jpg" alt={t(locale, 'Architecture in central Riyadh', 'معالم معمارية في وسط الرياض')} fill sizes="92vw" priority /><span className="photo-caption">{t(locale, 'Our perspective starts here.', 'تبدأ رؤيتنا من هنا.')}</span></div></div><section className="shell about-story section-space"><Eyebrow number="01">{t(locale, 'The firm', 'الشركة')}</Eyebrow><div><h2>{t(locale, 'Advice with your business in view.', 'مشورة تضع أعمالك في صميم اهتمامها.')}</h2><p className="large-copy">{t(locale, 'The most useful advice connects the detail with the bigger picture. What your numbers say. How your business operates. Where you want to go next.', 'تربط المشورة المفيدة التفاصيل بالصورة الأوسع: ما تعكسه أرقامك وكيف تعمل منشأتك وإلى أين تطمح في خطوتك القادمة.')}</p><p>{t(locale, 'Our services span financial audit, internal audit, tax, accounting, management consulting, and operations and technology. The starting point is always the same: understanding the question you need to answer.', 'تشمل خدماتنا المراجعة المالية والمراجعة الداخلية والضرائب والمحاسبة والاستشارات الإدارية والعمليات والتقنية. وتبقى نقطة البداية واحدة: فهم السؤال الذي تحتاج إلى إجابته.')}</p><TextLink href={localPath(locale, 'services')}>{t(locale, 'Explore our expertise', 'اكتشف خبراتنا')}</TextLink></div></section><section className="about-values"><div className="shell"><Eyebrow number="02">{t(locale, 'Our way of working', 'طريقتنا في العمل')}</Eyebrow><h2>{t(locale, 'Considered advice.', 'مشورة مدروسة.')}<br />{t(locale, 'Practical value.', 'وقيمة عملية.')}</h2><div className="values-grid">{[
    [t(locale, 'Understand the context', 'نفهم السياق'), t(locale, 'The right questions start with an understanding of your business, its people and its priorities.', 'تبدأ الأسئلة الصحيحة بفهم أعمالك وفريقك وأولوياتك.')],
    [t(locale, 'Make complexity clearer', 'نبسّط التعقيد'), t(locale, 'We aim to make financial and operational information easier to interpret and discuss.', 'نسعى إلى جعل المعلومات المالية والتشغيلية أسهل فهماً ومناقشة.')],
    [t(locale, 'Focus on what follows', 'نركز على الخطوة التالية'), t(locale, 'Advice should help you consider your choices and decide on a useful next step.', 'ينبغي أن تساعدك المشورة على تقييم خياراتك وتحديد خطوة تالية مفيدة.')],
  ].map(([title, body], index) => <div key={title}><span className="mono">{'0' + (index + 1)}</span><h3>{title}</h3><p>{body}</p></div>)}</div></div></section><section id="network-affiliation" className="shell network-section section-space"><div className="network-symbol" aria-hidden="true"><Globe /></div><div><Eyebrow number="03">{t(locale, 'Our connection', 'تواصلنا')}</Eyebrow><h2>{t(locale, 'Rooted here.', 'جذورنا هنا.')}<br /><span className="muted-heading">{t(locale, 'Connected internationally.', 'وتواصلنا عالمي.')}</span></h2><p>{t(locale, 'Kreston NBB Saudi is a member of the Kreston Global network. When an assignment crosses borders, that connection can bring relevant local knowledge and specialist perspectives into the conversation.', 'كريستون إن بي بي السعودية عضو في شبكة كريستون العالمية. وعندما تتجاوز الأعمال الحدود، يتيح هذا التواصل الاستفادة من المعرفة المحلية والرؤى المتخصصة ذات الصلة.')}</p><p className="small-copy">{t(locale, 'Kreston network members are independent firms. The scope of any cross-border engagement is agreed separately.', 'أعضاء شبكة كريستون شركات مستقلة. ويُتفق بصورة منفصلة على نطاق أي عمل دولي.')}</p></div></section><ContactBand locale={locale}/></>;
}

export function InsightsPage({ locale, insights }: { locale: Locale; insights: Insight[] }) {
  return <><PageIntro locale={locale} label={t(locale, 'Perspectives', 'رؤى')} title={t(locale, 'A clearer view of what matters.', 'رؤية أوضح لما يهمك.')} summary={t(locale, 'Ideas and questions to help you think through the next decision for your business.', 'أفكار وأسئلة تساعدك على التفكير في القرار القادم لأعمالك.')} /><section className="shell insights-listing"><InsightBrowser locale={locale} insights={insights} /><p className="editorial-note">{t(locale, 'Editorial previews prepared for this website concept. Content is subject to Kreston NBB review.', 'معاينات تحريرية أُعدّت لهذا التصور للموقع. المحتوى خاضع لمراجعة كريستون إن بي بي.')}</p></section><ContactBand locale={locale}/></>;
}
export function ArticlePage({ locale, insight }: { locale: Locale; insight: Insight }) {
  return <><section className="shell article-header"><Breadcrumb locale={locale} items={[{ name: t(locale, 'Perspectives', 'رؤى'), href: localPath(locale, 'insights') }, { name: t(locale, 'Article', 'مقال') }]} /><Eyebrow>{t(locale, 'A business perspective', 'رؤية في الأعمال')}</Eyebrow><h1>{pick(insight.title, locale)}</h1><p className="article-deck">{pick(insight.summary, locale)}</p><div className="article-byline"><span>{t(locale, 'Kreston NBB · Editorial preview', 'كريستون إن بي بي · معاينة تحريرية')}</span><span>{t(locale, 'Working copy', 'مسودة للمراجعة')}</span></div></section><div className="article-image shell"><div><Image src={insight.image} fill priority sizes="92vw" alt={t(locale, 'Saudi business and architecture', 'الأعمال والمعالم المعمارية في السعودية')} /></div></div><section className="article-layout shell section-space"><aside><Eyebrow>{t(locale, 'In this perspective', 'في هذه الرؤية')}</Eyebrow>{insight.sections.map((item, index) => <a key={index} href={'#section-' + index}>{pick(item.title, locale)}</a>)}</aside><div className="article-body">{insight.sections.map((item, index) => <section key={index} id={'section-' + index}><h2>{pick(item.title, locale)}</h2><p>{pick(item.body, locale)}</p></section>)}<p className="editorial-note">{t(locale, 'This is a draft editorial example for the website demo, adapted from the themes of the current website. It is general information, not advice for a particular business.', 'هذا مثال تحريري أولي للنسخة التجريبية، مستند إلى موضوعات الموقع الحالي. وهو معلومات عامة وليس مشورة لمنشأة بعينها.')}</p><TextLink href={localPath(locale, 'insights')}>{t(locale, 'Back to perspectives', 'العودة إلى الرؤى')}</TextLink></div></section><ContactBand locale={locale}/></>;
}
export function ContactPage({ locale, services }: { locale: Locale; services: Service[] }) {
  return <><PageIntro locale={locale} label={t(locale, 'Let’s talk', 'لنتحدث')} title={t(locale, 'What’s your next move?', 'ما خطوتك القادمة؟')} summary={t(locale, 'A question, a challenge, a new opportunity. Tell us what you have in mind.', 'سؤال أو تحدٍ أو فرصة جديدة. أخبرنا بما يشغلك.')} /><section className="shell contact-layout"><aside><Eyebrow>{t(locale, 'Start a conversation', 'ابدأ محادثة')}</Eyebrow><h2>{t(locale, 'Let’s find a clearer way forward.', 'لنجد طريقاً أوضح للمضي قدماً.')}</h2><p>{t(locale, 'Choose a service, or tell us a little about your business. This is the first step towards a more focused conversation.', 'اختر خدمة أو أخبرنا قليلاً عن أعمالك. هذه هي الخطوة الأولى نحو مناقشة أكثر تحديداً.')}</p><div className="contact-place"><span className="location-dot"/><div><strong>{t(locale, 'Riyadh', 'الرياض')}</strong><span>{t(locale, 'Saudi Arabia', 'المملكة العربية السعودية')}</span></div></div><div className="contact-photo"><Image src="/images/riyadh.jpg" fill sizes="(max-width: 800px) 100vw, 30vw" alt={t(locale, 'Riyadh architecture', 'معالم معمارية في الرياض')} /></div></aside><Suspense fallback={<p>{t(locale, 'Loading the enquiry form…', 'جارٍ تحميل نموذج الاستفسار…')}</p>}><EnquiryForm locale={locale} services={services}/></Suspense></section></>;
}
export function CareersPage({ locale }: { locale: Locale }) {
  return <><PageIntro locale={locale} label={t(locale, 'Careers', 'الوظائف')} title={t(locale, 'Bring your perspective.', 'أضف رؤيتك.')} summary={t(locale, 'An interest in business. A curiosity about the detail. A commitment to doing thoughtful work.', 'اهتمام بالأعمال وفضول تجاه التفاصيل والتزام بتقديم عمل مدروس.')} /><section className="careers-feature shell"><div className="career-image"><Image src="/images/saudi-business.jpg" fill priority sizes="(max-width: 800px) 100vw, 50vw" alt={t(locale, 'A business conversation', 'مناقشة أعمال')} /></div><div><Eyebrow>{t(locale, 'Grow your understanding', 'طوّر معرفتك')}</Eyebrow><h2>{t(locale, 'Good work begins with good questions.', 'يبدأ العمل الجيد بالأسئلة الصحيحة.')}</h2><p>{t(locale, 'Audit, accounting and advisory bring different perspectives to the same challenge: helping businesses understand their position and consider what comes next.', 'تقدم المراجعة والمحاسبة والاستشارات رؤى مختلفة لتحدٍ واحد: مساعدة الشركات على فهم وضعها وتقييم خطوتها القادمة.')}</p></div></section><section className="shell vacancies section-space"><Eyebrow>{t(locale, 'Opportunities', 'الفرص')}</Eyebrow><h2>{t(locale, 'Our next chapter.', 'فصلنا القادم.')}</h2><div className="vacancy-empty"><span className="mono">—</span><div><h3>{t(locale, 'Vacancies will be shared here.', 'سننشر الفرص الوظيفية هنا.')}</h3><p>{t(locale, 'No confirmed vacancies are listed in this website preview. Applications and CV uploads are not being collected.', 'لا تتضمن هذه المعاينة فرصاً وظيفية مؤكدة. لا تُجمع طلبات التوظيف أو السير الذاتية.')}</p></div></div></section></>;
}
export function PrivacyPage({ locale }: { locale: Locale }) {
  return <><PageIntro locale={locale} label={t(locale, 'Privacy & demo information', 'الخصوصية ومعلومات النسخة التجريبية')} title={t(locale, 'About this website preview.', 'حول معاينة هذا الموقع.')} summary={t(locale, 'A clear account of what this demonstration does with the information you enter.', 'توضيح لطريقة تعامل هذه النسخة التجريبية مع المعلومات التي تدخلها.')} /><section className="shell legal-content"><h2>{t(locale, 'The enquiry form', 'نموذج الاستفسار')}</h2><p>{t(locale, 'This demonstration validates form inputs in your browser. It does not send enquiries, store form contents, or upload documents. A success message means the validation demonstration is complete; it does not mean a message has reached Kreston NBB.', 'تتحقق هذه النسخة التجريبية من بيانات النموذج في متصفحك. ولا ترسل الاستفسارات أو تحفظ محتوى النموذج أو ترفع المستندات. تعني رسالة النجاح اكتمال تجربة التحقق، ولا تعني وصول رسالة إلى كريستون إن بي بي.')}</p><h2>{t(locale, 'Cookies and analytics', 'ملفات الارتباط والتحليلات')}</h2><p>{t(locale, 'No analytics, advertising scripts or tracking cookies are configured in this demo. Fonts and images are served by the application. The web server may process ordinary technical requests needed to deliver the pages.', 'لا تتضمن هذه النسخة التجريبية أدوات تحليلات أو إعلانات أو ملفات ارتباط للتتبع. تُقدّم الخطوط والصور من التطبيق. وقد يعالج خادم الويب الطلبات التقنية المعتادة اللازمة لعرض الصفحات.')}</p><h2>{t(locale, 'Working content', 'محتوى قيد المراجعة')}</h2><p>{t(locale, 'This is a design and functionality preview. English and Arabic copy, service wording, photography rights and company information require review before publication. The imagery is sourced from the existing Kreston NBB website and does not identify any person as an employee.', 'هذه معاينة للتصميم والوظائف. تتطلب النصوص العربية والإنجليزية وصياغة الخدمات وحقوق الصور ومعلومات الشركة مراجعة قبل النشر. الصور مصدرها موقع كريستون إن بي بي الحالي، ولا تُعرّف أي شخص بوصفه موظفاً.')}</p><h2>{t(locale, 'Before public launch', 'قبل الإطلاق العام')}</h2><p>{t(locale, 'Kreston NBB must provide its approved privacy notice and confirm the contact details, data handling and delivery systems before live enquiries are enabled. This page describes the demonstration only.', 'يجب أن تقدم كريستون إن بي بي إشعار الخصوصية المعتمد وتؤكد بيانات الاتصال وآلية التعامل مع البيانات وأنظمة الإرسال قبل تفعيل الاستفسارات الفعلية. تصف هذه الصفحة النسخة التجريبية فقط.')}</p><TextLink href={localPath(locale, 'contact')}>{t(locale, 'Return to the enquiry form', 'العودة إلى نموذج الاستفسار')}</TextLink></section></>;
}

